name: takion
description: "A Metron Comic Database Mobile Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  dio: ^5.9.1
  path_provider: ^2.1.5
  json_annotation: ^4.11.0
  freezed_annotation: ^3.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  synchronized: ^3.4.0
  flex_color_scheme: ^8.4.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  auto_route: ^11.1.0
  flash: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
  freezed: ^3.2.5
  riverpod_generator: ^4.0.3
  hive_ce_generator: ^1.11.0
  auto_route_generator: ^10.4.0


flutter:

  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Italic.ttf
          style: italic
